# Generated by Django 5.0.4 on 2024-04-24 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_newsletters_alter_contacts_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='telephone',
        ),
    ]
