# Generated by Django 5.0.4 on 2024-04-22 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='telephone',
            field=models.CharField(blank=True, error_messages={'invalid': 'Votre numéro de téléphone ne doit pas contenir des espaces.', 'required': 'Ce champ est obligatoire.'}, max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format '+221612345678'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
